# @note: This migration in generated by `rails g model Session user:references token:string:uniq last_used_at:datetime active:boolean:index`
class CreateSessions < ActiveRecord::Migration[7.0]
  def change
    create_table :sessions do |t|
      t.references :user, null: false, foreign_key: true
      t.string :token
      t.datetime :last_used_at
      t.boolean :active, default: true

      t.timestamps
    end
    add_index :sessions, :token, unique: true
    add_index :sessions, :active
  end
end
